# Generated by Django 6.0 on 2025-12-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_seller_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
