# Generated by Django 6.0 on 2025-12-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seller_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='slug',
        ),
    ]
