# Generated by Django 6.0 on 2025-12-26 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('times_added_to_cart', models.IntegerField(default=0)),
                ('times_added_to_wishlist', models.IntegerField(default=0)),
                ('view_to_cart_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_to_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Аналитика товара',
                'verbose_name_plural': 'Аналитика товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.product')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('results_count', models.IntegerField(default=0, help_text='Количество найденных товаров')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_product', models.ForeignKey(blank=True, help_text='Товар, на который кликнули после поиска', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-searched_at'],
            },
        ),
    ]
