# Generated by Django 6.0 on 2025-12-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'Просмотры товара', 'verbose_name_plural': 'Просмотры товаров'},
        ),
    ]
